export const CONTENT_ROOT_ID = 'dialog-content-root'
export const CSS_STYLESHEET = 'index.css'
export const DIALOG_Z_INDEX = Number.MAX_SAFE_INTEGER - 1
export const DIALOG_TOOLTIP_Z_INDEX = Number.MAX_SAFE_INTEGER
export const SELECTION_DELAY_MS = 300
export const DIALOG_HEIGHT = 640
export const DIALOG_WIDTH = 640
export const DIALOG_POSITION_PADDING = 8
export const ICON_CHANGE_DELAY_MS = 1000
export const SCROLLBAR_HIDE_TIMER_MS = 0
export const OPEN_DIALOG_COMBINATION_MODIFIER_KEY = 'shiftKey'
export const OPEN_DIALOG_COMBINATION_SECOND_KEY = 'D'
export const MAX_CHAT_TOPK = 8
export const MAX_CHAT_TEMPERATURE = 1
export const DEFAULT_CHAT_TEMPERATURE = 1
export const DEFAULT_CHAT_TOPK = 3
